### ISSUE TITLE
Exposing clearDrawing 

### ISSUE THREAD

**Issue by edvincandon** [jgrancher/react-native-sketch#11]
I've successfully exposed the clearDrawing method for external components to clear the current drawing, but before I send my pull request, I was wondering how you want to handle the current clear button? 

If we expose the clearDrawing method, the button becomes obsolete.. Maybe activate it through props?

I'm also working on an undo/redo method, but it's kind of going beyond the scope of a simple sketch component..

**Comment by thekevinbrown** [comment]
I've already submitted a PR for this: https://github.com/jgrancher/react-native-sketch/pull/13

I handled it as a prop that sets the clear button as hidden.

**Comment by edvincandon** [comment]
Oh I missed it! 

Your version is a lot cleaner actually, I used the RCTBridge's uiManager to get it working which kinda complicated the call from javascript.. Kudos! 

👍
