### ISSUE TITLE
Circle

### ISSUE THREAD

**Issue by Rainer2465** [jgrancher/react-native-sketch#21]
I have:
`var color1 = "rgb(" + this.state.red * 255 + ",0,0)"
    var color2 = "rgb(0," + this.state.green * 255 + ",0)"
    var color3 = "rgb(0,0," + this.state.blue * 255 + ")"
    var red = this.state.red * 255
    var blue = this.state.blue * 255
    var green = this.state.green * 255
    var stroke = "rgb(" + this.state.red * 255 + "," + this.state.green * 255 + "," +  this.state.blue * 255  + ")"
 `
`<Slider
          value={this.state.red}
          thumbTintColor = {color1}
          onValueChange={(red) => this.setState({red})} />`

how can I change slider to circle?
`<Circle
          value={this.state.red}
          thumbTintColor = {Pink}
          onValueChange={(red) => this.setState({red})} />`

would this work?

**Comment by jgrancher** [comment]
Hi @Rainer2465! It seems that your issue isn't related to react-native-sketch, I don't know anything about a `<Slider />` or a `<Circle />` component! :)

**Comment by Rainer2465** [comment]
Alright thanks 😃
