### ISSUE TITLE
Transparent background black

### ISSUE THREAD

**Issue by Rainer2465** [jgrancher/react-native-sketch#22]
<img width="375" alt="bildschirmfoto 2017-01-19 um 20 16 13" src="https://cloud.githubusercontent.com/assets/25153882/22121386/262f20ee-de84-11e6-8e31-ae793c58e6c0.png">

what can I do?

**Comment by jgrancher** [comment]
Yeh, it's a known issue. :/ We're actually working on a solution in this issue #8... Will let you know how it goes!

**Comment by jgrancher** [comment]
It's been fixed! See my comments here: #8
