### ISSUE TITLE
Change #import "RCTXxx.h" to <React/RCTXxx.h> to solve compile error

### ISSUE THREAD

**Issue by jaybowang** [jgrancher/react-native-sketch#29]
I'm using React Native 0.44. There are a couple of compile errors after I added this useful component.
The error said `Duplicate interface definition for class 'RCTView'`. It's the same with other classes like RCTBridge, RCTEventDispatcher, etc.

I found a [solution](https://github.com/shoutem/ui/issues/134#issuecomment-273977589) and it works for me. 
Just change `#import "RCTXxx.h"` to `#import <React/RCTXxx.h>`.

I'll send a PR later.

**Comment by jaybowang** [comment]
I found it's already `#import <React/Xxx.h>` right after I forked.
__EXCEPT__ one import in  `RNSketchManager.h`.

Please release the latest code to npm. Thanks. 👍

**Comment by jgrancher** [comment]
Hi @jaybowong,
This is due to RN's change of headers since v0.40. You'll find the correction on the master branch, or on this PR #28 that will be merged soon (and pushed to npm too)!

**Comment by jaybowang** [comment]
Thank you @jgrancher

**Comment by jaybowang** [comment]
Hi,  @jgrancher When will you release a new version? It's been 19 days. 

I can change the code on my computer to make it work but team work will be better if you release this fix.

**Comment by peacechen** [comment]
`#if` may be used to conditionally support RN <0.40 as well as RN >= 0.40.  I'll create a PR for this.

Update: Created PR #31 to support RN 0.4x while retaining backwards compatibility. This is the preferred method of importing RN headers.

**Comment by jaybowang** [comment]
I just found that I can specify the exact commit that I want to use. No need to change code on my computer. No need to wait for a new release.

In `package.json` file:
```
"react-native-sketch": "git+https://github.com/jgrancher/react-native-sketch.git#40b2510"
```

**Comment by jgrancher** [comment]
@jaybowong You can now use the last version and it should work!
