### ISSUE TITLE
Native component for "RNSketch" does not exist

### ISSUE THREAD

**Issue by jasoncollins111** [jgrancher/react-native-sketch#3]
Im getting this error when I require Sketch and it doesn't seem to be working.

**Comment by jgrancher** [comment]
@SaintEmbers Can you please provide a code example and the react-native version you're using so that I can have a look? :)

**Comment by jgrancher** [comment]
@SaintEmbers Have you run the command `rnpm link react-native-sketch` after the npm install?
(you can also directly run `rnpm install react-native-sketch` that combines npm install and rnpm link)

**Comment by jasoncollins111** [comment]
@jgrancher I did rnpm install react-native-sketch and it added it to the project but it still wasn't linking for some reason, I also tried rnpm link react-native-sketch to no avail.  I had to manually add the library through XCode.  I did that by right clicking on the file and then selecting 'Add files to <project>'  and then going into node modules and adding the RNSketch folder.  Thanks for getting back to me!

**Comment by jgrancher** [comment]
@SaintEmbers Hmm ok, seems strange. I'll add the manual installation instructions to the Readme at some point! Glad it worked anyway.

**Comment by lkmtue** [comment]
@jgrancher: Have you tested it on Android? I'm having the same issue with Android.

**Comment by jgrancher** [comment]
@lkmtue Unfortunately, it's not compatible with Android yet. :/ (But PR are welcome if you know a bit of Java!)

**Comment by kalli8** [comment]
I'm having this same issue as @SaintEmbers. I can't figure out how to add it manually. Please help!

**Comment by Sonezi** [comment]
Also a same issue, for some reason it doesnt work, a don't have any errors regarding link and install, but in implementation it won't work. just saying Warning: Native component for "RNSketch" does not exist.. :) any help?

**Comment by becnichelesmith** [comment]
Heya! I'm using Expo and am getting this error "Native component for "RNSketch" does not exist"

I already ran `rnpm install react-native-sketch`.

**Comment by jgrancher** [comment]
@Sonezi Have you run `react-native link react-native-sketch`? What version do you use? What do you see on the screen?

**Comment by pawansingewar007** [comment]
same issue with react native 0.51

**Comment by gopinathrpt** [comment]
same issue with react native 0.52

**Comment by mvdwaeter** [comment]
same issue with react-native 0.54.2 (iOS)
I have run react-native link react-native-sketch
Also tried the way of @SaintEmbers , but no luck.
```
npm-install info Linking react-native-sketch ios dependency
rnpm-install info Platform 'ios' module react-native-sketch has been successfully linked
```

**Comment by dylanklohr** [comment]
How did anyone end up resolving this?

**Comment by gopinathrpt** [comment]
It's work fine

**Comment by skptricks** [comment]
It is not working...

**Comment by skptricks** [comment]
It is not working... please fix for android app

**Comment by jgrancher** [comment]
@skptricks Sorry, it's not meant to work on Android, as mentioned in the `README.md` file.
