### ISSUE TITLE
It is not working.

### ISSUE THREAD

**Issue by ohsei** [jgrancher/react-native-sketch#30]
I use mouse as input.
Can not draw anything on the screen.
why?

**Comment by jgrancher** [comment]
@ohsei, can you try again now? A new version has been released, which should now work. Otherwise, give me some specifics and I'll try to help 😉

**Comment by gulukul** [comment]
Not working for me too. This is what is seen on the simulator.

<img width="378" alt="screen shot 2017-10-03 at 3 53 06 pm" src="https://user-images.githubusercontent.com/18757846/31152932-2323337e-a853-11e7-974b-a15c19f9b68d.png">

This is my 'index.io.js' file
<img width="576" alt="screen shot 2017-10-03 at 3 55 12 pm" src="https://user-images.githubusercontent.com/18757846/31152971-4d7f4586-a853-11e7-9061-94a6bf4a7405.png">

**Comment by richaseh** [comment]
Not working for me too. This is what is seen on the simulator.

<img width="378" alt="screen shot 2017-10-03 at 3 53 06 pm" src="https://user-images.githubusercontent.com/18757846/31152932-2323337e-a853-11e7-974b-a15c19f9b68d.png">

This is my 'index.io.js' file
<img width="576" alt="screen shot 2017-10-03 at 3 55 12 pm" src="https://user-images.githubusercontent.com/18757846/31152971-4d7f4586-a853-11e7-9061-94a6bf4a7405.png">

**Comment by jgrancher** [comment]
Hey @richaseh, thanks for your feedback.
I've tried your code, and it works well for me (see screenshot below)!

Here are the steps I've followed:
- `react-native init SketchTest`
- `cd SketchTest`
- `yarn add react-native-sketch`
- `react-native link react-native-sketch`  **Make sure you don't forget this one!**
- Replaced `index.js`with the snippet below.

(The 3rd step is essential. I think I've already had this kind of results in the past when I had forgotten to link the module.)

**Snippet:**

```javascript
import React from 'react';
import { Alert, Button, View, AppRegistry } from 'react-native';
import Sketch from 'react-native-sketch';

export default class SketchTest extends React.Component {
  save = () => {
    this.sketch.save().then(({ path }) => {
      Alert.alert('Image saved!', path);
    });
  };

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Sketch
          ref={sketch => {
            this.sketch = sketch;
          }}
          strokeColor="#ff69b4"
          strokeThickness={3}
        />
        <Button onPress={this.save} title="Save" />
      </View>
    );
  }
}

AppRegistry.registerComponent('SketchTest', () => SketchTest);
```

**Results:**

![simulator screen shot - iphone 6 - 2017-10-04 at 17 05 48](https://user-images.githubusercontent.com/5517450/31161959-4ec0867a-a926-11e7-9f22-752eb1ac50b6.png)

Hope this helps!

If that still doesn't work, please make sure you use a recent version of React Native (tested here with `0.48.4`), and `react-native-sketch` `^1.0.0`.

**Comment by jgrancher** [comment]
@richaseh Did that work for you?

**Comment by hojjatazimi** [comment]
Hi
I  have the same problem with react-native 0.49.3.
I've done all the instructions above with no result.

**Comment by hojjatazimi** [comment]
@jgrancher
Hi
I have the same problem with react-native 0.49.3.
I've done all the instructions above with no result.

**Comment by ata-kaya** [comment]
@jgrancher 
Hi 
I have the same problem with react-native 0.46.1

**Comment by jgrancher** [comment]
@hojjatazimi @omid-zamani Thanks for letting me know. Do you guys use Expo?

**Comment by ata-kaya** [comment]
Thanks for your attention. it was my wrong. I checked it in android so it didn't work. I'm writing android side of it. I'll send pr when it finishes.

**Comment by jgrancher** [comment]
Closing this issue for now. (Expo / Android are separate issues!)
