### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by jasoncollins111** [jgrancher/react-native-sketch#4]
How exactly do I access onReset?  It seems likes its built in to the canvas without a way to trigger it.  Thanks!

**Comment by jgrancher** [comment]
@SaintEmbers Yeh, it's actually in my roadmap.
I need to find a way to trigger the reset from an outer component (it didn't work properly when I started working on it, so I put that feature aside for the first release.)

For now, you can still play with the `_clearButton` property that triggers it in RNSketch.m, setting its position, title... : https://github.com/jgrancher/react-native-sketch/blob/master/RNSketch/RNSketch.m#L62

**Comment by thekevinbrown** [comment]
I submitted https://github.com/jgrancher/react-native-sketch/pull/13 for this.

**Comment by thekevinbrown** [comment]
Now that #15 has been merged I think we can close this issue.

**Comment by jgrancher** [comment]
@SaintEmbers : @blargity is right, his work has been merged and you can now directly call `mySketch.clear()` which will reset the drawing. Closing the issue :)
