### ISSUE TITLE
This Lib simply DOESN'T support Android

### ISSUE THREAD

**Issue by JohnnyDevX** [jgrancher/react-native-sketch#46]
and there is no word about it in the docs...
thanks for wasted time.
The author probably thinks that Android users are peasants and he doesn't give a fu*k... typical Apple consumer

**Comment by kev71187** [comment]
It says it right in the docs. It also says he doesn't know android development and wants help. 

![image](https://user-images.githubusercontent.com/2372855/51639389-c5dc0c00-1f2e-11e9-82d5-88eeed9f0139.png)

stay grateful

**Comment by jgrancher** [comment]
Thanks @kev71187!
@JohnnyDevX Indeed, it says right on the README that this library doesn't support Android (I'll make it clearer though).
You probably should know that this is an open source library, which means people work on it on their spare time. Staying polite and grateful is the minimum you could do.
