### ISSUE TITLE
Not rendering properly

### ISSUE THREAD

**Issue by sambwest** [jgrancher/react-native-sketch#5]
Hi,

Any ideas what I"m doing wrong? I have copied and pasted the example into a view and I just get a red line on the left and nowhere to write. I get the same result on an Android device and the IOS simulator.

Any help appreciated!

Thanks,

Sam

![screen shot 2016-07-08 at 16 34 29](https://cloud.githubusercontent.com/assets/6604613/16702175/fa0d9944-4529-11e6-9d70-196727a558dd.png)

**Comment by jgrancher** [comment]
Hi @sambwest,
Can you give me in details the steps you've done to end up with that result? I've already seen this screen, and it was when I hadn't `rnpm link` the component properly.

Just to be sure it's working, I've done:
- `react-native init TestSketch`
- `cd TestSketch`
- `npm i react-native-sketch`
- `rnpm link react-native-sketch`
- I copied and pasted the example from the Readme in a new file `Signature.js`
- In index.ios.js, I've added this line: `import Signature from './Signature';`
- Then I set the render method of TestSketch to look like:

```
<View style={styles.container}>
    <Signature />
</View>
```

And it worked fine to me.

**Comment by sambwest** [comment]
Hi,

Thanks for having a look. Many rebuilds later it linked ok. I noticed after testing it on a device that it was working ok. 
Thanks
