### ISSUE TITLE
Is it possible to draw on a transparent background?

### ISSUE THREAD

**Issue by aprihodko** [jgrancher/react-native-sketch#8]
I am asking as I want to draw over image but do not change the existing image.
Thanks

**Comment by mozillo** [comment]
+1

**Comment by abdullah-shiwani** [comment]
+1

**Comment by stantoncbradley** [comment]
Should work the same as overlaying anything else over an image?

```
<Image>
  <Sketch
          fillColor="transparent"
          strokeColor={`hsl(${this.state.strokeColor}, 100%, 50%)`}
          strokeThickness={4}
          onReset={this.onReset}
          onUpdate={this.onUpdate}
          ref={(sketch) => { this.sketch = sketch; }}
          style={styles.container}
          resizeMode="contain"
        >
          <Image />
  </Sketch>
</Image>
```

Have you tried that?

**Comment by aprihodko** [comment]
Sure
          fillColor="transparent"

does not make an image visible

**Comment by MacKentoch** [comment]
It would be outstanding to be able to draw over image.

I cross my finger!

**Comment by elingersin1** [comment]
+ 1

**Comment by elingersin1** [comment]
+1

**Comment by gastonmorixe** [comment]
`UIGraphicsBeginImageContextWithOptions(self.bounds.size, NO, 0);`
That "NO" means "No Opaque". In RNSketch.m

**Comment by aprihodko** [comment]
I made it possible https://github.com/aprihodko/react-native-sketch

**Comment by jgrancher** [comment]
Hi there,
Thanks guys, I didn't realize that this use case would be in such demand.

@aprihodko Do you think you can submit a PR with that work you had done? :)
Although, I think your commits will be in conflict with #16 (about handling the image types), right?  🤔

**Comment by andreip-svitla-sge** [comment]
@jgrancher My version creates a PNG type sketches to keep a transparency. I can make a PR if you wish

**Comment by aprihodko** [comment]
@jgrancher My version creates a PNG type sketches to keep a transparency. I can make a PR if you wish

**Comment by jgrancher** [comment]
@aprihodko Oh yes, I would definitely love a PR that takes [this commit](https://github.com/aprihodko/react-native-sketch/commit/b1d58ba74c547c04ea5648c8b323dd71366546a7) in, if you've got time! :)

**Comment by jgrancher** [comment]
It is now included! (Thanks to your work @aprihodko!)
You'll have to use `fillColor="transparent"` along with `imageType="png"` in order to get a transparent background and export a transparent `.png` image.

You can access it from the `master` branch or `0.5.0` version.
(🚨 Although, the `0.5.0` version doesn't contain the RN 0.40 compatibility fix; This is because I'm doing a major bump today for it!)
